const buttons = document.querySelectorAll("button");
for (let button of buttons) {
  button.addEventListener('click', () => {
    let playerSelection = '';
    switch (button.id){
      case 'rock':
        playerSelection = 'Rock';
        break;
      case 'paper':
        playerSelection = 'Paper'
        break;
      case 'scissors':
        playerSelection = 'Scissors'
        break;
    }
    playRound(playerSelection, getComputerChoice());
  });
};

//getComputerChoice will randomly return 'Rock', 'Paper' or 'Scissors'

function getComputerChoice() {
  const OPTIONS = ['Rock', 'Paper', 'Scissors'];
  let randomIndex = Math.floor(Math.random() * 3);
  return OPTIONS[randomIndex];
}
// Function that let's user play one game, takes two parameters - 
// playerChoice and computerChoice which is generated by getComputerChoice()

function playRound(playerSelection, computerSelection) {
  let win = `You win! ${playerSelection} beats ${computerSelection}!`;
  let failure = `You lose! ${playerSelection} is beaten by ${computerSelection}!`;
  let tie = `It's a tie! ${playerSelection} ties with ${computerSelection}.`;
  if (playerSelection === computerSelection) {
    console.log(tie);
    return 'tie';
  } else if (playerSelection === 'Rock') {
    if (computerSelection === 'Paper') {
      console.log(win);
      return 'player';
    } else if (computerSelection === 'Scissors') {
      console.log(failure);
      return 'computer';
    }
  } else if (playerSelection === 'Paper') {
    if (computerSelection === 'Rock') {
      console.log(win);
      return 'player';
    } else if (computerSelection === 'Scissors') {
      console.log(failure);
      return 'computer';
    }
  } else if (playerSelection === 'Scissors') {
    if (computerSelection === 'Paper') {
      console.log(win);
      return 'player';
    } else if (computerSelection === 'Rock') {
      console.log(failure);
      return 'computer';
    }
  } else {
    return 'Upsss, something went wrong!';
  }
}