//getComputerChoice will randomly return 'Rock', 'Paper' or 'Scissors'

function getComputerChoice() {
  const OPTIONS = ["Rock", "Paper", "Scissors"];
  let randomIndex = Math.floor(Math.random() * 3);
  return OPTIONS[randomIndex];
}


// Function that let's user play one game, takes two parameters - 
// playerChoice and computerChoice which is generated by getComputerChoice()

function playRound(playerSelection, computerSelection) {
  let win = `You win! ${playerSelection} beats ${computerSelection}!`;
  let failure = `You lose! ${playerSelection} is beaten by ${computerSelection}!`;
  let tie = `It's a tie! ${playerSelection} ties with ${computerSelection}.`;
  let err = `${playerSelection} is not a valid option. Choose between 'Rock', 'Paper' or 'Scissors'`;
  if (playerSelection === computerSelection) {
    return tie;
  } else if (playerSelection === "Rock") {
    if (computerSelection === "Paper") {
      return win;
    } else if (computerSelection === "Scissors") {
      return failure;
    }
  } else if (playerSelection === "Paper") {
    if (computerSelection === "Rock") {
      return win;
    } else if (computerSelection === "Scissors") {
      return failure;
    }
  } else if (playerSelection === "Scissors") {
    if (computerSelection === "Paper") {
      return win;
    } else if (computerSelection === "Rock") {
      return failure;
    }
  } else {
    return err;
  }
}

function game() {
  let userInput = prompt("Type your choice: Rock, Paper or Scissors:");
  let playerSelection = userInput.charAt(0).toUpperCase() + userInput.slice(1).toLowerCase();

}